/* Pure paid-plan logic. No network, payment, storage, or DOM access. */
globalThis.BookedNext30 = (() => {
 'use strict';
 const VERSION='career-v1';
 const PRICE=49;
 const roles={
  color:{label:'Colorist',unit:'color appointment',buyer:'client',proof:'a color result you want to do more of',source:'past color clients, referrals, and local search',tool:'COLOR APPOINTMENT MATH'},
  cut:{label:'Cutting + styling',unit:'cut or styling appointment',buyer:'client',proof:'a cut or style you want more of',source:'returning clients, local referrals, and search',tool:'CUT + STYLE MATH'},
  extensions:{label:'Extension specialist',unit:'install or maintenance visit',buyer:'client',proof:'an install with a clear maintenance plan',source:'qualified consultations and referrals',tool:'EXTENSION APPOINTMENT MATH'},
  session:{label:'Session / editorial / commercial',unit:'paid job',buyer:'producer, brand, or booking contact',proof:'a small set of work that fits the jobs you want',source:'past teams, producers, brands, and your rep if you have one',tool:'WHOLE-JOB MATH'},
  bridal:{label:'Bridal + event stylist',unit:'wedding or event booking',buyer:'bride, client, or planner',proof:'a real event result with the services and location made clear',source:'planners, venues, photographers, past clients, and search',tool:'BRIDAL BOOKING MATH'},
  education:{label:'Educator + beauty brand work',unit:'class or brand assignment',buyer:'salon, student, or brand contact',proof:'one clear skill people leave able to use',source:'salons, brands, past students, and industry contacts',tool:'CLASS + BRAND JOB MATH'},
  owner:{label:'Salon owner',unit:'salon workday',buyer:'salon client',proof:'the team’s work and a clear reason to choose the salon',source:'salon referrals, local relationships, search, and past clients',tool:'SALON DAY MATH'},
  manager:{label:'Salon manager',unit:'pay period',buyer:'owner or person you report to',proof:'one clear improvement you helped the team make',source:'the team, front desk, owner, and the reports you can access',tool:'YOUR PAY + YOUR TIME'},
  restart:{label:'Starting or returning to hair',unit:'paid appointment',buyer:'client',proof:'recent work that shows the service you want to book',source:'people who know your work, local contacts, and recent models',tool:'FIRST APPOINTMENT MATH'},
  other:{label:'Another kind of hair career',unit:'paid assignment',buyer:'person who hires or pays you',proof:'a clear example of the work people can hire you for',source:'past buyers, referrals, and people who hire for your kind of work',tool:'YOUR WORK, YOUR MATH'}
 };
 const examples={
  color:{problem:'The appointment pays $300. It takes more than the time on the booking screen.',action:'Record the consultation, color used, finish, and cleanup for one appointment before changing the price.',earned:300,costs:55,hours:4,breakdown:'$40 color and supplies + $15 allocated work costs. 3.5 hours with the client + 0.5 hour setup and cleanup.',answers:{color_pay:'self',color_product:'rough',color_time:'often'}},
  bridal:{problem:'A $1,000 wedding booking includes a trial, an assistant, and travel.',action:'Check the full booking cost and ready-by time before agreeing to another person or location.',earned:1000,costs:400,hours:12,breakdown:'$250 assistant + $100 travel + $50 supplies. 2 hours trial + 2 travel + 6 event + 2 prep and admin.',answers:{bridal_team:'team',bridal_quote:'services',bridal_trial:'bundled',bridal_changes:'absorb'}},
  session:{problem:'An $800 job takes 14 hours once prep, travel, and wrap are counted.',action:'Confirm the full schedule, costs, and approval contact before accepting the next job.',earned:800,costs:120,hours:14,breakdown:'$80 unreimbursed travel + $40 supplies. 2 hours prep + 2 travel + 9 on set + 1 wrap and invoicing. No agency deduction in this example.',answers:{session_agency:'me',session_scope:'late',session_overrun:'absorb'}}
 };
 const goals=[['clients','More of the right paid work.'],['money','Better pay for the work I already do.'],['return','More repeat business or referrals.'],['keep','Know where the money goes. Keep more of it.'],['time','More life outside work.'],['stable','A steadier business and some breathing room.'],['help','Help me pick the first move.']];
 const question=(id,title,choices,purpose,extra={})=>({id,title,choices,purpose,...extra});
 const unknown=['unknown','Honestly? I need to check.'];
 // Each role answer has a concrete response. Its priority tags determine where it appears.
 const rq=(id,title,choices,tags,actions,extra={})=>question(id,title,choices,'Changes the '+tags.join('/')+' action for this career.',{tags,actions,...extra});
 const roleQuestions={
  color:[
   rq('pay','HOW DOES YOUR PAY WORK?',[['commission','The salon pays me a percentage.'],['hourly','I’m paid by the hour.'],['self','I keep the service money and pay my work costs.'],['mixed','More than one way.']],['money','keep'],{commission:'Check the amount you receive after the salon’s share. A service total is not your paycheck.',hourly:'Use paid hours and actual pay. Ask how service results affect raises or bonuses before chasing a bigger sales number.',self:'Include the color and supplies you paid for when checking an appointment.',mixed:'Check each pay setup separately before comparing appointments.'}),
   rq('control','WHO CAN CHANGE YOUR PRICES OR BOOKING TIMES?',[['me','I can.'],['together','I need the salon’s agreement.'],['salon','The salon decides.']],['money','time'],{me:'Test one change on one service after checking its actual time and cost.',together:'Bring one real appointment example to the person who approves prices and timing.',salon:'Ask for one specific timing or pay discussion. Do not promise a price change you cannot make.'}),
   rq('signature','WHAT COLOR WORK DO YOU WANT MORE OF?',[['blonde','Blondes and lived-in color.'],['maintenance','Root color and regular maintenance.'],['correction','Corrections and big changes.'],['creative','Creative or vivid color.'],['mix','A mix.']],['clients','return'],{blonde:'Show a result with the upkeep explained. Make the consultation and booking path easy to find.',maintenance:'Show how regular maintenance fits into a real calendar. Give existing clients a clear next-visit recommendation.',correction:'Lead with a consultation. Explain that the starting hair affects the time, cost, and number of visits.',creative:'Show the finished color and what maintaining it involves. Let the right client know what they are signing up for.',mix:'Choose one color service to feature this week so the offer is easy to understand.'}),
   rq('time','DO COLOR APPOINTMENTS FINISH WHEN YOU BOOKED THEM TO?',[['yes','Usually.'],['sometimes','Some run over.'],['often','The schedule is optimistic. Very optimistic.'],unknown],['time','money'],{yes:'Protect the timing that works, including cleanup and breaks.',sometimes:'Time the next 3 appointments in the service that runs late most often.',often:'Record consultation, application, processing, finish, and cleanup separately for one real appointment.',unknown:'Write down the actual start and finish for your next 3 color clients.'}),
   rq('product','DO YOU KNOW WHAT COLOR AND SUPPLIES COST PER VISIT?',[['yes','Yes, I track it.'],['rough','Roughly.'],['no','No. The mixing bowl has secrets.'],['covered','The salon pays for it.']],['keep','money'],{yes:'Compare one appointment’s supply cost with another doing the same service.',rough:'Record what you actually mix for 3 visits before changing what you charge.',no:'Start with one visit: record the color and supplies used, plus obvious waste.',covered:'Keep salon-paid supplies out of your personal work-cost calculation.'}),
   rq('consult','WHAT GETS CLEAR BEFORE YOU START?',[['clear','Goal, upkeep, price, and time.'],['look','Mostly the look they want.'],['price','Price comes up later than it should.'],['varies','It depends on the client.']],['return','money'],{clear:'Turn that conversation into a short repeatable checklist.',look:'Add upkeep, the price for today, and the time available before mixing.',price:'Say the agreed price and what is included before the service starts.',varies:'Use the same 4 points with every color client: result, upkeep, price, time.'}),
   rq('return','WHAT HAPPENS BEFORE A COLOR CLIENT LEAVES?',[['plan','We agree on the next visit and when.'],['ask','I ask if they want to rebook.'],['desk','The front desk handles it.'],['nothing','We say goodbye and hope.']],['return','stable'],{plan:'Track whether the agreed next visit is reserved and completed.',ask:'Recommend what comes next and when before asking for a booking.',desk:'Give the front desk the service and timing you recommended.',nothing:'End the next 3 visits with one specific maintenance recommendation.'})
  ],
  cut:[
   rq('pay','HOW DOES YOUR PAY WORK?',[['commission','The salon pays me a percentage.'],['hourly','I’m paid by the hour.'],['self','I keep the service money and pay my work costs.'],['mixed','More than one way.']],['money','keep'],{commission:'Check your share of the service, then any costs you personally pay.',hourly:'Compare actual pay with all required hours. Service sales alone do not tell us your pay.',self:'Count your costs and the whole appointment, including cleanup.',mixed:'Keep each pay setup separate when comparing the work.'}),
   rq('control','WHO CAN CHANGE YOUR PRICES OR APPOINTMENT TIMES?',[['me','I can.'],['together','We decide together.'],['salon','The salon decides.']],['money','time'],{me:'Check 3 real appointments before testing one price or timing change.',together:'Bring the actual appointment times to the person who approves the schedule.',salon:'Ask for a specific timing or pay review using one real workday.'}),
   rq('specialty','WHAT WORK DO YOU WANT MORE OF?',[['cuts','Cuts and shape changes.'],['texture','Curls, coils, or texture-focused work.'],['short','Short cuts or barbering.'],['styling','Blowouts and styling.'],['mix','A mix.']],['clients','return'],{cuts:'Show the shape, the finish, and who that cut suits. Give one clear way to book.',texture:'Show the work and explain what a first appointment includes, including home styling guidance.',short:'Show consistent finished work and make the maintenance visit easy to reserve.',styling:'Describe the occasion or result you serve and the time people should allow.',mix:'Pick one service to feature this week. A long menu is not a clear invitation.'}),
   rq('time','HOW ACCURATE ARE YOUR APPOINTMENT TIMES?',[['fit','They usually fit.'],['late','I often run late.'],['gaps','I lose time in gaps.'],['varies','Different clients need very different times.']],['time','money'],{fit:'Protect the time for consultation, finish, and cleanup.',late:'Record the actual start and finish of your next 5 visits.',gaps:'Check one week for gaps you can reduce without removing breaks.',varies:'Compare a maintenance visit with a big change. They may need different booking times.'}),
   rq('consult','DO CLIENTS KNOW HOW TO LIVE WITH THE CUT AT HOME?',[['yes','We talk through styling and upkeep.'],['sometimes','Sometimes.'],['rushed','The finish gets rushed.'],['unknown','I need to ask.']],['return'],{yes:'Ask at their next visit what worked at home and what did not.',sometimes:'Add one practical styling tip and a maintenance recommendation to every finish.',rushed:'Reserve a few minutes to show the client how to style the result themselves.',unknown:'Ask the next 3 returning clients what felt easy or difficult at home.'}),
   rq('return','HOW DO YOU HANDLE THE NEXT VISIT?',[['recommend','I recommend when and what to book.'],['ask','I ask if they want to book again.'],['desk','The front desk handles it.'],['wait','I wait for them to contact me.']],['return','stable'],{recommend:'Track whether the next visit actually happens.',ask:'Explain when the shape will need attention, then offer the appointment.',desk:'Pass the recommended service and timing to the desk.',wait:'Give the next 5 clients a clear recommendation before they leave.'}),
   rq('extras','WHAT HAPPENS WHEN THE SERVICE GETS BIGGER?',[['clear','We agree on extra work and price first.'],['free','I tend to throw it in.'],['salon','The salon sets what is included.'],['unclear','Honestly, the boundaries are fuzzy.']],['money','time'],{clear:'Keep the explanation simple and consistent.',free:'Choose one frequent extra. Check its time and cost before deciding when to give it away.',salon:'Ask for clarity about what is included and how to book extra work.',unclear:'Write down what the base service includes and what needs extra time.'})
  ],
  extensions:[
   rq('pay','HOW DOES YOUR EXTENSION PAY WORK?',[['commission','I get a percentage.'],['hourly','I’m paid by the hour.'],['self','I keep the service money and pay the costs.'],['mixed','It varies.']],['money','keep'],{commission:'Separate the amount you earn from hair purchases and the salon’s share.',hourly:'Use actual paid hours and pay. A large install price is not automatically a large paycheck.',self:'Separate hair cost, supplies, appointment time, and money left for you.',mixed:'Compare one job at a time with its actual pay arrangement.'}),
   rq('hair','WHO PAYS FOR THE HAIR BEFORE YOU ORDER IT?',[['client','The client pays first.'],['me','I often pay first.'],['salon','The salon handles it.'],['varies','It depends.']],['keep','stable'],{client:'Keep the hair payment separate from what you earn for the service.',me:'Record how much cash is tied up in hair orders and when you get it back.',salon:'Check what the salon pays and what is deducted from your pay.',varies:'Write down the payment arrangement for each order before purchasing hair.'}),
   rq('quote','WHAT DOES YOUR QUOTE MAKE CLEAR?',[['all','Hair, install, upkeep, and removal.'],['install','Mostly hair and installation.'],['verbal','We mostly talk it through.'],['unknown','I need a clearer system.']],['return','money'],{all:'Check that the client understands the ongoing visits, not just day one.',install:'Add maintenance timing and removal costs before the client commits.',verbal:'Send a short written recap of what was agreed.',unknown:'Create a quote checklist: hair, install, maintenance, removal, and what is included.'}),
   rq('timing','DO YOU TRACK INSTALLS AND MAINTENANCE SEPARATELY?',[['yes','Yes. Different time and money.'],['rough','Roughly.'],['no','I lump them together.']],['money','time'],{yes:'Compare one install and one maintenance visit using the money each leaves you per hour.',rough:'Record the actual time and supplies for one of each.',no:'Split the two types of appointment before deciding which work pays best.'}),
   rq('maintenance','DO CLIENTS LEAVE WITH A MAINTENANCE PLAN?',[['booked','Yes, and the next visit is booked.'],['plan','They have a plan but book later.'],['chase','I end up chasing them.'],['new','I’m still building this.']],['return','stable'],{booked:'Track completed maintenance visits, not just reservations.',plan:'Offer the next appropriate maintenance visit before checkout.',chase:'Confirm the next visit and how reminders will work while the client is still with you.',new:'Make maintenance timing part of your first consultation.'}),
   rq('adjustments','WHAT HAPPENS WITH UNPLANNED FIXES OR EXTRA TIME?',[['clear','I know what is included and track it.'],['free','A lot becomes unpaid extra work.'],['rare','It rarely comes up.'],['unknown','I haven’t tracked it.']],['keep','time'],{clear:'Compare the extra time with the original booking estimate.',free:'Record the next 3 adjustments and why they happened before changing a policy.',rare:'Keep your explanation of included follow-up clear.',unknown:'Start a simple log of extra visits, time, supplies, and the reason.'}),
   rq('stock','HOW MUCH HAIR IS SITTING AROUND UNUSED?',[['little','Very little. I order for booked work.'],['some','Some leftovers.'],['lots','My shelf is an expensive roommate.'],['unknown','I need to count it.']],['keep','stable'],{little:'Keep ordering tied to booked work.',some:'List what you have before placing the next order.',lots:'Count usable stock and its cost. Stop buying duplicates you already own.',unknown:'Do one stock check before your next hair order.'})
  ],
  session:[
   rq('market','WHAT KIND OF JOBS DO YOU WANT MORE OF?',[['commercial','Commercial and brand campaigns.'],['editorial','Editorial.'],['celebrity','Talent, celebrity, or red carpet.'],['production','Film, TV, or production.'],['mix','A mix.']],['clients'],{commercial:'Build a small portfolio selection that fits the brands you want to hire you.',editorial:'Separate portfolio-building work from the paid jobs that support your income.',celebrity:'Make your relevant work, availability contact, and location easy for the right teams to find.',production:'Show experience and availability relevant to the production work you want.',mix:'Choose one type of buyer to approach first this month.'}),
   rq('agency','WHO HANDLES YOUR BOOKINGS?',[['rep','A rep or agency.'],['me','I do.'],['both','Both.']],['clients','money'],{rep:'Agree with your rep on the jobs you want and what information you need before accepting.',me:'Use one short booking checklist for every inquiry.',both:'Clarify which relationships and follow-ups belong to you and which belong to your rep.'}),
   rq('scope','WHAT IS CONFIRMED BEFORE YOU SAY YES?',[['clear','Rate, hours, location, and what the job includes.'],['rate','Usually just the rate and date.'],['late','The details tend to arrive later.']],['money','time'],{clear:'Keep the written scope with the booking so changes are easy to discuss.',rate:'Ask about prep, expected hours, location, kit needs, and the payment contact before agreeing.',late:'Hold your answer until the details needed to judge the job are clear.'}),
   rq('overrun','WHAT HAPPENS WHEN THE JOB RUNS LONG?',[['agreed','We already agreed how extra time is handled.'],['ask','I have to bring it up on the day.'],['absorb','I usually absorb the time.'],unknown],['money','time'],{agreed:'Record actual start and finish against what was agreed.',ask:'Confirm the process for extra time before the next booking.',absorb:'Track prep, travel, time on set, and wrap for the next job.',unknown:'Find the booking terms and the person who can approve a change before the job starts.'}),
   rq('expenses','DO YOU FRONT MONEY FOR JOB EXPENSES?',[['often','Often.'],['sometimes','Sometimes.'],['never','Rarely or never.']],['keep','stable'],{often:'Keep fronted expenses and expected reimbursements separate from earned fees.',sometimes:'Record the amount, approval, receipt, and repayment date for each expense.',never:'Count only the costs you actually pay when checking what the job leaves you.'}),
   rq('payment','HOW QUICKLY DOES THE MONEY ARRIVE?',[['fast','Within 2 weeks.'],['month','More than 2 weeks, up to a month.'],['slow','More than a month.'],['varies','It varies, and I chase it.']],['keep','stable'],{fast:'Keep invoice and payment records together so you can see what remains unpaid.',month:'Keep upcoming bills separate from money still on invoices.',slow:'List unpaid invoices, due dates, and the person to contact.',varies:'Confirm the invoice process and payment contact before your next job.'}),
   rq('followup','WHAT HAPPENS AFTER A GOOD JOB?',[['contact','I stay in touch with the team.'],['rep','My rep handles it.'],['portfolio','I update my work when I have permission.'],['nothing','I wait for the next call.']],['clients','return'],{contact:'Choose 3 good contacts for a useful, specific check-in this month.',rep:'Agree on a follow-up with your rep so nobody gets conflicting messages.',portfolio:'Share a relevant update with the people who hire for that work.',nothing:'Send one short thank-you and keep the booking contact where you can find it again.'})
  ],
  bridal:[
   rq('team','HOW DO YOU WORK EVENTS?',[['solo','Mostly solo.'],['team','I book and lead a team.'],['contract','I work on someone else’s team.'],['mix','A mix.']],['money','time'],{solo:'Build travel, setup, breaks, and cleanup into the booking time.',team:'Separate team pay from what the booking leaves you.',contract:'Confirm your pay, call time, duties, and who handles schedule changes.',mix:'Compare solo, lead, and team-member work separately.'}),
   rq('inquiry','WHERE DO GOOD INQUIRIES COME FROM?',[['referrals','Past clients and referrals.'],['vendors','Planners, venues, and other vendors.'],['search','Search or my website.'],['social','Social media.'],['unknown','I need to track it.']],['clients'],{referrals:'Make a simple way for happy clients to introduce someone with a real date and location.',vendors:'Choose 3 vendors whose events fit your work for a personal introduction.',search:'Make service area, availability contact, portfolio, and inquiry steps easy to find.',social:'Give the portfolio a clear inquiry link that asks for the date, place, and party size.',unknown:'Ask every inquiry how they found you for the next 30 days.'}),
   rq('quote','WHAT IS INCLUDED IN YOUR QUOTE?',[['clear','Services, party size, travel, timing, and extras.'],['services','Mostly the services.'],['custom','It is different every time.']],['money','keep'],{clear:'Compare the final schedule with the quote before the event.',services:'Add travel, early starts, assistants, and extra time where they apply.',custom:'Use the same quote checklist even when the price is custom.'}),
   rq('trial','HOW DOES THE TRIAL OR PREVIEW WORK?',[['clear','Its price and purpose are clear.'],['bundled','It is included, but I don’t check its cost.'],['informal','The plan is pretty informal.'],['none','My work doesn’t include a trial.']],['money','return'],{clear:'Send a short recap of the agreed look and what may need changing.',bundled:'Count trial time and supplies when checking the whole booking.',informal:'Set a clear purpose, time allowance, and agreed next step.',none:'Use another clear way to confirm the requested look and event details.'}),
   rq('timeline','WHEN IS THE GETTING-READY SCHEDULE SET?',[['early','Before the event, with a clear finish time.'],['late','Usually late in the process.'],['day','Sometimes on the day.']],['time','return'],{early:'Share the schedule and confirm who handles changes.',late:'Request the ready-by time, services, and locations before finalizing your schedule.',day:'Create the schedule ahead of the next event. Wedding morning has enough hobbies.'}),
   rq('changes','WHAT HAPPENS WHEN THE PARTY OR LOCATION CHANGES?',[['written','We confirm the change and price in writing.'],['verbal','We discuss it, mostly by text.'],['absorb','I often just make it work.']],['money','time'],{written:'Keep the latest agreed scope in one place for everyone involved.',verbal:'Send one final written recap of the people, services, places, timing, and price.',absorb:'Before accepting an addition, check whether it needs more time, travel, or another stylist.'}),
   rq('after','WHAT HAPPENS AFTER THE EVENT?',[['system','I have a simple thank-you and review/referral follow-up.'],['photos','I mostly ask for photos.'],['nothing','I move on to the next one.']],['return','clients'],{system:'Track which follow-ups lead to a review, referral, or vendor relationship.',photos:'With permission, use images alongside a brief thank-you and review request.',nothing:'Send a short thank-you and make it easy to leave a review or introduce you to someone.'})
  ],
  education:[
   rq('buyer','WHO PAYS FOR YOUR EDUCATION WORK?',[['salons','Salons or salon groups.'],['brand','A beauty brand or distributor.'],['students','Stylists book and pay directly.'],['mixed','More than one.']],['clients','money'],{salons:'Describe the team problem the class solves and what the salon receives.',brand:'Confirm the teaching, preparation, content, travel, and reporting expected.',students:'Make the learning outcome, level, format, and what is included clear before people book.',mixed:'Compare each kind of buyer separately. A brand assignment and a ticketed class have different costs.'}),
   rq('format','WHAT ARE YOU SELLING FIRST THIS MONTH?',[['live','In-person education.'],['online','Live online education.'],['resource','A recorded class or resource.'],['brand','Brand training or content.']],['clients','time'],{live:'Confirm model, room, equipment, supplies, and who handles setup.',online:'Test the link, sound, demonstration setup, and how people ask questions.',resource:'Make the result, access instructions, and support included easy to understand.',brand:'Confirm the required teaching or content, deadlines, and approval contact.'}),
   rq('outcome','CAN YOU SAY WHAT PEOPLE WILL LEAVE ABLE TO DO?',[['clear','Yes, in one sentence.'],['topic','I can name the topic. The outcome is fuzzy.'],['broad','I am trying to teach everything.']],['clients','return'],{clear:'Put that outcome at the top of the offer and check it at the end of the class.',topic:'Finish this sentence: “After this, you can…” Use a practical skill.',broad:'Choose one useful outcome for this offer. Save the rest for another class.'}),
   rq('prep','DO YOU COUNT PREP AND FOLLOW-UP AS WORK TIME?',[['yes','Yes. All of it.'],['some','Some of it.'],['no','Only the hours I teach.']],['money','time'],{yes:'Compare the whole assignment with what it pays after costs.',some:'Add slide prep, model prep, travel, messages, and follow-up to the next job record.',no:'Time one assignment from preparation through the last promised follow-up.'}),
   rq('expenses','WHO HANDLES TRAVEL, MODELS, AND SUPPLIES?',[['written','It is agreed before booking.'],['me','A lot comes out of my fee.'],['unclear','We usually sort it out later.'],['none','Those costs do not apply to my work.']],['keep','money'],{written:'Keep costs paid by the buyer separate from costs you absorb.',me:'List those costs before deciding whether the fee works for you.',unclear:'Confirm who pays, any approval needed, and how repayment works before booking.',none:'Still include any platform or payment fees you actually pay.'}),
   rq('followup','WHAT SUPPORT DO PEOPLE GET AFTERWARD?',[['clear','A specific resource or limited follow-up.'],['unlimited','They can message me whenever.'],['none','Nothing is promised.'],['varies','It changes with every booking.']],['time','return'],{clear:'Make the support and its limits clear in the offer.',unlimited:'Decide what support is included and when you answer. Endless DMs are work.',none:'Consider one small recap people can use without creating an unlimited support job.',varies:'Write the support agreement into the booking recap.'}),
   rq('proof','HOW DO YOU KNOW THE EDUCATION HELPED?',[['results','I collect examples of people using it.'],['feedback','I ask for feedback.'],['repeat','People book me again.'],['unknown','I have not checked.']],['return','clients'],{results:'With permission, show one practical result from someone who used the lesson.',feedback:'Ask one specific question about what they can now do differently.',repeat:'Ask what earned the repeat booking so you know what to preserve.',unknown:'Send a short check-in asking what they used and where they got stuck.'})
  ],
  owner:[
   rq('model','HOW DOES THE SALON MAKE MONEY?',[['employees','Employee or commission team.'],['renters','Chair or suite rentals.'],['mixed','A mix of rentals and employees.'],['solo','Mostly my own client work.']],['money','keep'],{employees:'Keep payroll, salon costs, and your own pay separate when checking the month.',renters:'Track collected rent, available space, and building costs separately from your personal service income.',mixed:'Give rental income and team service income their own lines. They are different businesses inside one building.',solo:'Separate the pay for your own services from what the salon itself costs to run.'}),
   rq('pay','DO YOU KNOW WHAT THE SALON LEAVES FOR YOU?',[['clear','Yes. It is separate from sales.'],['rough','Roughly.'],['bank','I mostly look at the bank balance.'],['unknown','I need a proper picture.']],['money','keep'],{clear:'Compare a normal month with the next using the same cost categories.',rough:'Gather one complete normal month of income and work bills.',bank:'Keep money due for bills separate from money available to pay yourself.',unknown:'Start with collected income, payroll, rent, supplies, fees, and your own pay.'}),
   rq('bookings','WHERE IS THE EMPTY SPACE?',[['everywhere','Across most of the team or stations.'],['some','Only certain people or days.'],['full','The salon is busy.'],['unknown','I need the numbers.']],['clients','money'],{everywhere:'Choose one service and source of clients before adding another big expense.',some:'Pick one quiet person or day for a focused booking plan.',full:'Check what the busy work leaves after costs before trying to fit in more people.',unknown:'Look at one normal week by stylist, station, or rented space.'}),
   rq('team','WHAT TEAM ISSUE NEEDS THE MOST ATTENTION?',[['hiring','Finding or keeping the right people.'],['standards','Consistent client experience.'],['training','Training and support.'],['none','The team is working well.'],['solo','It is just me.']],['stable','return'],{hiring:'Write down the actual role, schedule, pay arrangement, and support before trying to fill it.',standards:'Agree on one client-experience standard the whole team can use this week.',training:'Choose one skill to practice in a short team session.',none:'Ask what helps the team work well and protect it.',solo:'Choose one repeat task you can simplify before adding help.'}),
   rq('return','HOW DOES REBOOKING WORK ACROSS THE SALON?',[['shared','Stylists and desk have a clear handoff.'],['stylist','Every stylist does their own thing.'],['desk','The desk is expected to handle it.'],['unknown','We need a clearer system.']],['return','clients'],{shared:'Track completed return visits alongside reserved appointments.',stylist:'Agree on a simple next-visit conversation and handoff.',desk:'Give the desk the recommended service and timing before checkout.',unknown:'Choose who recommends the next visit, who books it, and who follows up.'}),
   rq('stock','HOW ARE PRODUCTS AND SUPPLIES ORDERED?',[['tracked','We check stock and usage first.'],['habit','Mostly habit and whoever notices.'],['lots','We have too much sitting around.'],['unknown','I need to look.']],['keep'],{tracked:'Check one frequently used product for waste or duplicate purchases.',habit:'Assign one stock check and one ordering list.',lots:'Count usable stock before buying more. Your shelf is not a savings account.',unknown:'Start with the products you buy most often and what is already on hand.'}),
   rq('delegation','WHAT STILL NEEDS YOU EVERY TIME?',[['everything','Nearly everything.'],['people','Staff and client problems.'],['admin','Schedules, orders, and paperwork.'],['little','Most daily work runs without me.']],['time','stable'],{everything:'Pick one recurring decision someone else can handle within clear limits.',people:'Agree what the team can resolve and when it should come to you.',admin:'Document one repeat task and give it a clear owner.',little:'Protect the system and look for the next useful improvement instead of taking tasks back.'})
  ],
  manager:[
   rq('pay','HOW ARE YOU PAID FOR MANAGING?',[['salary','Salary.'],['hourly','Hourly.'],['bonus','Base pay plus a bonus or percentage.'],['mixed','Management plus my own client work.']],['money','keep'],{salary:'Compare one normal pay period with all the hours management takes.',hourly:'Check that your record includes the required work you actually do.',bonus:'Get clear about which results affect the bonus and when it is paid.',mixed:'Separate management pay and hours from your own client pay and hours.'}),
   rq('authority','WHAT CAN YOU ACTUALLY CHANGE?',[['clear','My responsibilities and limits are clear.'],['ask','Most changes need the owner.'],['unclear','I’m responsible, but the authority is fuzzy.']],['time','money','stable'],{clear:'Choose one improvement within those limits and tell the owner how you will measure it.',ask:'Bring the owner one specific proposal, the decision needed, and a date to revisit it.',unclear:'Ask which decisions belong to you, which need approval, and what success means.'}),
   rq('responsibility','WHAT IS ON YOUR PLATE?',[['schedule','Schedules and bookings.'],['team','Staff support and training.'],['clients','Client concerns and service standards.'],['stock','Stock, orders, or costs.'],['numbers','Reports and business targets.']],['time','stable'],{schedule:'Set one repeat time to review the schedule rather than fixing it all day.',team:'Choose one team issue for a short, specific check-in.',clients:'Agree which client concerns you can resolve and when the owner steps in.',stock:'Keep one current ordering list and a clear approval limit.',numbers:'Choose one report you can access and one number you are expected to improve.'},{multi:true}),
   rq('reports','CAN YOU SEE THE NUMBERS YOU ARE EXPECTED TO IMPROVE?',[['yes','Yes.'],['some','Some, but not all.'],['no','Not really.'],['unclear','The targets themselves need work.']],['money','keep'],{yes:'Use one report consistently so you can see whether the change helped.',some:'Ask for the missing report tied to your responsibility.',no:'Request access or a regular report before accepting responsibility for a number you cannot see.',unclear:'Agree on one measurable target with the owner.'}),
   rq('handoff','WHAT HAPPENS WHEN A PROBLEM NEEDS THE OWNER?',[['clear','We have a clear handoff.'],['wait','I wait and keep following up.'],['mine','It tends to stay on my plate.']],['time','stable'],{clear:'Keep the decision and next step in one place.',wait:'Send the issue, your recommendation, and the decision needed together.',mine:'Clarify where your responsibility ends and who handles the next decision.'}),
   rq('team','WHAT IS THE BIGGEST TEAM BOTTLENECK?',[['coverage','Coverage and scheduling.'],['standards','Inconsistent service or expectations.'],['training','People need training or support.'],['communication','Things get lost between people.'],['none','The team is running well.']],['return','clients','time'],{coverage:'Review one week for predictable coverage gaps before they become emergencies.',standards:'Choose one standard and show what it looks like in practice.',training:'Teach one repeatable skill in a short session.',communication:'Use one clear place for the shift handoff and unresolved issues.',none:'Protect what works and choose a different problem to solve.'}),
   rq('offduty','DOES THE JOB FOLLOW YOU HOME?',[['rare','Rarely. Boundaries are clear.'],['messages','Messages keep coming.'],['work','I do regular work after my paid day.'],['always','Off duty seems theoretical.']],['time','money'],{rare:'Keep the handoff that makes those boundaries possible.',messages:'Agree on response times and who handles an urgent issue after your shift.',work:'Record that work alongside your paid hours, then discuss it with the owner.',always:'Agree on one protected finish time and who is responsible after it.'})
  ],
  restart:[
   rq('starting','WHERE ARE YOU STARTING FROM?',[['new','New to paid hair work.'],['return','Returning after time away.'],['move','New place, new clientele.'],['rebuild','Rebuilding after a change.']],['clients','stable'],{new:'Start with one service you can deliver confidently and a clear way to book it.',return:'Choose one current skill or service to refresh before trying to rebuild everything.',move:'Make your location and booking details obvious everywhere people find your work.',rebuild:'Choose which past relationships and services you want to bring into this version of the business.'}),
   rq('setup','DO YOU HAVE A PLACE OR WAY TO DO PAID WORK?',[['ready','Yes. Ready to book.'],['salon','I’m looking for a salon role.'],['space','I’m arranging independent work or a space.'],['exploring','I’m still deciding.']],['clients','stable'],{ready:'Put the booking steps in one clear link or message.',salon:'List what you need from the role: training, schedule, pay setup, and client support.',space:'List the actual costs and requirements before committing to a space.',exploring:'Compare one employed option and one independent option using real costs and support.'}),
   rq('service','WHAT DO YOU WANT TO LEAD WITH?',[['color','Color.'],['cut','Cutting or styling.'],['extensions','Extensions.'],['events','Bridal, events, or location work.'],['unsure','I need to choose.']],['clients'],{color:'Feature one color service with clear consultation and maintenance expectations.',cut:'Show one cut or styling result and make the appointment easy to understand.',extensions:'Start with a clear consultation, hair-cost plan, and maintenance offer.',events:'Make your service area, availability contact, and type of event clear.',unsure:'Pick one service you enjoy, can deliver well, and can show proof of.'}),
   rq('proof','DO YOU HAVE RECENT WORK TO SHOW?',[['yes','Yes.'],['old','Mostly older work.'],['some','A few useful examples.'],['none','I need to build it.']],['clients'],{yes:'Choose a small set that matches the service you want to sell.',old:'Create one current example before rebuilding the whole portfolio.',some:'Use the strongest example with a clear description and booking step.',none:'Plan one model service with clear expectations and permission for any photos you want to use.'}),
   rq('network','WHO ALREADY KNOWS YOUR WORK?',[['past','Past clients.'],['colleagues','Former colleagues or salons.'],['local','People in my local community.'],['none','I’m starting pretty fresh.']],['clients'],{past:'Reach out personally to a few past clients who would welcome an update.',colleagues:'Tell a few former colleagues what kind of work you are taking now.',local:'Make one real introduction where your potential clients already spend time.',none:'Start with one local relationship and one clear example of your work.'},{multi:true,exclusive:['none']}),
   rq('barrier','WHAT IS MAKING THE FIRST STEP HARD?',[['confidence','I need my confidence back.'],['skills','I want more practice or training.'],['setup','The work setup is not ready.'],['clients','I’m ready. I need people to book.']],['clients','stable'],{confidence:'Choose one small service or conversation you can complete this week.',skills:'Name one skill to practice and find a focused way to practice it.',setup:'Finish the next practical setup step before spending on promotion.',clients:'Make one specific booking offer to people who are a good fit.'}),
   rq('schedule','WHAT CAN YOU REALISTICALLY OFFER RIGHT NOW?',[['one','One reliable day or block each week.'],['few','A few days.'],['full','A full workweek.'],['changing','It changes week to week.']],['time','stable'],{one:'Build around that reliable block and say clearly when it is available.',few:'Choose consistent booking days where you can.',full:'Fill demand gradually. An open schedule is not a reason to spend on everything at once.',changing:'Give clients a clear way to see or request your next available dates.'})
  ],
  other:[
   rq('format','WHAT DOES YOUR PAID WORK LOOK LIKE?',[['appointments','Appointments with individual clients.'],['projects','Jobs or projects.'],['employment','An employed role.'],['products','Education, content, or products.'],['mixed','A mix.']],['money','clients'],{appointments:'Choose one appointment type to check from booking through follow-up.',projects:'Check one assignment from the first message to the final payment.',employment:'Use your actual pay and responsibilities rather than treating employer sales as your income.',products:'Check one offer, the buyer it serves, and what it costs to deliver.',mixed:'Separate the work types before comparing time and money.'}),
   rq('buyer','WHO USUALLY PAYS YOU?',[['person','Individual clients.'],['business','Businesses or brands.'],['employer','An employer.'],['mixed','More than one.']],['clients','money'],{person:'Make the result, price, and booking step easy for a client to understand.',business:'Make the work, fee, responsibilities, and payment contact clear.',employer:'Ask which responsibilities and results can change your pay.',mixed:'Choose one kind of buyer to focus on for this plan.'}),
   rq('scope','ARE THE WORK AND PAY AGREED BEFORE YOU START?',[['yes','Usually, yes.'],['some','Some details are clear.'],['no','Too much gets sorted out later.']],['money','time'],{yes:'Keep a written recap where both sides can find it.',some:'Confirm the missing detail before the next assignment.',no:'Use a short scope recap: what you will do, when, what it pays, and what is extra.'}),
   rq('sources','HOW DOES PAID WORK FIND YOU?',[['repeat','People who hired me before.'],['referrals','Referrals.'],['online','Online work or search.'],['direct','I reach out directly.'],['unknown','I need to track it.']],['clients','return'],{repeat:'Choose a useful check-in with a past buyer.',referrals:'Make it easy for a happy buyer to introduce someone.',online:'Connect one relevant example directly to a booking or inquiry step.',direct:'Send a small number of specific messages to suitable buyers.',unknown:'Ask the next 5 buyers how they found you.'},{multi:true,exclusive:['unknown']}),
   rq('costs','DO YOU KNOW WHAT EACH JOB LEAVES YOU?',[['yes','Yes.'],['rough','Roughly.'],['no','Not yet.'],['salary','I’m paid a wage or salary.']],['keep','money'],{yes:'Compare two jobs using the same costs and total hours.',rough:'Gather the actual payments and bills for one job.',no:'Start with one job’s earned pay, your costs, and total time.',salary:'Compare actual pay with total required work time.'}),
   rq('repeat','IS REPEAT BUSINESS PART OF THIS WORK?',[['yes','Yes, and it happens.'],['want','Yes, but I want more of it.'],['referral','It is more about referrals.'],['not','Not really.']],['return'],{yes:'Find out what earned the repeat booking and preserve it.',want:'Agree on a natural next step at the end of the work.',referral:'Ask satisfied buyers for a relevant introduction.',not:'Focus on finding the next suitable buyer rather than forcing a repeat offer.'}),
   rq('time','WHERE DOES UNPLANNED TIME GO?',[['prep','Prep or setup.'],['travel','Travel.'],['messages','Messages and admin.'],['changes','Extra work or changes.'],['none','It is mostly under control.']],['time'],{prep:'Time the prep for one assignment and include it in the job record.',travel:'Count required travel when checking the value of the job.',messages:'Give admin a specific block and a clear response window.',changes:'Confirm added time and any changed pay before agreeing to extra work.',none:'Protect the boundaries that already work.'})
  ]
 };
 // These describe current work and a feasible plan, not a second personality quiz.
 function primary(a={}){
  const lanes=Array.isArray(a.careers)?a.careers.filter(x=>roles[x]):[];
  return lanes.length===1?lanes[0]:lanes.includes(a.primary)?a.primary:null;
 }
 function goalFor(a={}){
  if(a.goal&&a.goal!=='help')return a.goal;
  const role=primary(a),qs=roleQuestions[role]||[];
  if(a.load==='starting'||a.load==='open')return 'clients';
  for(const q of qs){if(['unknown','no','unclear','bank','rough'].includes(a[role+'_'+q.id])&&q.tags.includes('keep'))return 'keep'}
  return a.load==='full'?'time':'money';
 }
 function questions(a={}){
  const role=primary(a),goal=goalFor(a);
  const out=[question('careers','WHAT KIND OF HAIR CAREER ARE WE WORKING ON?',Object.entries(roles).map(([key,value])=>[key,value.label]),'Route the plan to the actual work.',{multi:true,note:'Pick all that apply. We’ll focus one plan at a time.'})];
  if((a.careers||[]).length>1)out.push(question('primary','WHICH PART OF YOUR CAREER GETS THE FIRST PLAN?',a.careers.filter(x=>roles[x]).map(x=>[x,roles[x].label]),'Choose the current focus without discarding other work.',{note:'You can build and save another plan for another part of your career.'}));
  if(!role)return out;
  out.push(question('goal','WHAT WOULD MAKE THE NEXT 30 DAYS WORTH IT?',goals,'Set one measurable starting priority.',{note:'Pick one to start with. We are not fixing your entire life by Tuesday.'}));
  out.push(question('load',role==='owner'||role==='manager'?'HOW BUSY IS THE SALON RIGHT NOW?':'HOW MUCH PAID WORK DO YOU HAVE RIGHT NOW?',[
   ['starting','Starting or rebuilding. Not much paid work yet.'],['open','Some work. Plenty of room for more.'],['busy','Busy, with some room.'],['full','Full, or close to it.'],unknown
  ],'Distinguish building demand from improving existing work.'));
  out.push(question('available','HOW MUCH TIME CAN YOU GIVE THIS EACH WEEK?',[
   ['tiny','About 15 minutes. Start small.'],['hour','About an hour.'],['two','About 2 hours.'],['more','3 hours or more.']
  ],'Size the tasks to the time the person can actually use.'));
  if(goal==='clients')out.push(question('budget','WHAT CAN YOU SPEND ON FINDING WORK THIS MONTH?',[
   ['0','$0. Use what I already have.'],['100','$1-$100.'],['300','$101-$300.'],['more','More than $300, if the plan makes sense.']
  ],'Keep client-finding actions inside the available budget.'));
  for(const q of roleQuestions[role]){
   const copy={...q,id:role+'_'+q.id};
   if((role==='bridal'&&q.id==='inquiry')||(role==='session'&&q.id==='followup')){
    copy.multi=true;copy.exclusive=role==='bridal'?['unknown']:['nothing'];
   }
   if(['signature','specialty','market'].includes(q.id))copy.note='Pick one to focus on first this month.';
   out.push(copy);
  }
  if(goal==='stable'){
   out.push(question('savings','IF WORK STOPPED, HOW LONG COULD SAVINGS COVER THE BILLS?',[
    ['none','I haven’t built that cushion yet.'],['month','Less than 2 months.'],['few','2 to under 6 months.'],['solid','6 months or more.'],unknown
   ],'Choose between finding the baseline and protecting an existing cushion.'));
   out.push(question('savinghabit','IS PUTTING MONEY ASIDE HAPPENING?',[
    ['bills','The bills get there first.'],['irregular','Sometimes. Income is uneven.'],['regular','Yes, regularly.'],['unknown','I need to check.']
   ],'Avoid assuming money is available to save.'));
  }
  return out;
 }
 function choices(q){return q.choices||[]}
 function cleanAnswers(input={}){
  if(!input||typeof input!=='object'||Array.isArray(input))input={};
  const a={};
  // Rebuild the visible path after each accepted answer. Unknown keys never survive.
  for(let pass=0;pass<6;pass++)for(const q of questions(a)){
   const raw=input[q.id],allowed=new Set(q.choices.map(x=>x[0]));
   if(q.multi){
    const vals=[...new Set((Array.isArray(raw)?raw:raw===undefined?[]:[raw]).filter(v=>allowed.has(v)))];
    const exclusive=vals.find(v=>(q.exclusive||[]).includes(v));
    if(vals.length)a[q.id]=exclusive?[exclusive]:vals;
   }else if(allowed.has(raw))a[q.id]=raw;
  }
  return Object.fromEntries(questions(a).filter(q=>a[q.id]!==undefined).map(q=>[q.id,a[q.id]]));
 }
 function complete(a){const clean=cleanAnswers(a);return questions(clean).every(q=>clean[q.id]!==undefined&&(!q.multi||clean[q.id].length>0))}
 function seed(free={},legacy={}){
  const map={color:'color',cut:'cut',extensions:'extensions',session:'session',events:'bridal',education:'education',owner:free.leadershiprole==='manager'?'manager':'owner',inactive:'restart',other:'other'};
  const a={careers:[...new Set((free.worktype||[]).map(k=>map[k]).filter(Boolean))]};
  const primaryMap={'chair-color':'color','chair-cut':'cut','chair-extensions':'extensions',session:'session',events:'bridal',education:'education',management:free.leadershiprole==='manager'?'manager':'owner',notearning:'restart',other:'other'};
  if(a.careers.includes(primaryMap[free.primarywork]))a.primary=primaryMap[free.primarywork];
  const role=primary(a);
  const goal=free.goalpriority||(Array.isArray(free.goal)?free.goal.length===1?free.goal[0]:null:free.goal);
  if(goals.some(x=>x[0]===goal))a.goal=goal;
  const loads={notyet:'starting',under25:'open',half:'open',threequarters:'busy',full:'full',light:'open',busy:'busy'};
  if(loads[free.full||free.workload])a.load=loads[free.full||free.workload];
  if(role&&['color','cut','extensions'].includes(role)){
   const pay={commission:'commission',hourly:'hourly',self:'self',mixed:'mixed'}[free.paymodel];
   if(pay)a[role+'_pay']=pay;
  }
  if(free.savings)a.savings=free.savings;
  return cleanAnswers(a);
 }
 const playbooks={
  color:{stop:'STOP LETTING THE PRICE DO ALL THE TALKING.',instead:'Check time, color used, your pay setup, and the agreed result together.',checklist:['Starting hair and relevant service history','Result agreed for this visit','Price and what is included','Time booked, including finish and cleanup','Maintenance discussed','Next visit recommended'],scripts:[
   ['CONSULTATION','For today, we’re aiming for [result]. Based on your starting hair, I recommend [plan]. Today is [price] and about [time]. Keeping it looking like this means [upkeep]. Does that work for you?'],
   ['NEXT VISIT','To keep this color looking like this, I recommend [service] around [timing]. Want me to reserve that while we have the calendar open?'],
   ['CLEAR SCOPE','That extra work needs [time] and would make today’s total [price]. We can do [option today] or book a separate visit. Which works better for you?']
  ]},
  cut:{stop:'STOP BOOKING EVERY CUT AS THE SAME JOB.',instead:'Match the time to the work, including the consultation and finish.',checklist:['What the client likes and wants changed','Home styling time and routine','Agreed shape or finish','Time needed for a restyle versus maintenance','One useful home styling tip','Recommended next visit'],scripts:[
   ['CONSULTATION','What do you like about your hair right now, and what is driving you mad? How much styling do you realistically want to do at home?'],
   ['NEXT VISIT','This shape will need attention around [timing]. I recommend [service] next. Shall we find a time that works?'],
   ['EXTRA WORK','We booked [service]. A bigger change needs [extra time]. Here are the options that let me do it properly: [options].']
  ]},
  extensions:{stop:'STOP CALLING THE HAIR PURCHASE YOUR PAY.',instead:'Separate the hair, supplies, installation, upkeep, and your own time.',checklist:['Consultation and suitability discussion','Hair order and who pays before ordering','Install time and price','Maintenance timing and cost','Home-care expectations','Removal and adjustment process'],scripts:[
   ['QUOTE RECAP','Here’s the plan: [hair], [install], and [maintenance schedule]. The agreed total for this visit is [price]. Future maintenance is [price or how it is quoted]. We’ll confirm the order and booking once [agreed next step].'],
   ['MAINTENANCE','Your next maintenance visit should be around [timing]. Let’s reserve it now so the plan does not depend on both of us remembering later.'],
   ['ADDITIONAL WORK','This is outside the work we originally booked. I can offer [option] with [time and price]. Let’s agree on that before we start.']
  ]},
  session:{stop:'STOP JUDGING THE JOB BY THE HEADLINE RATE.',instead:'Count prep, travel, set time, wrap, costs, and the wait for payment.',checklist:['Date, location, call time, expected finish','Scope and required kit or prep','Agreed fee and approval contact','How extra time or added work is handled','Who pays expenses and how they are approved','Invoice details, payment contact, and agreed timing'],scripts:[
   ['BEFORE ACCEPTING','Thanks for thinking of me. Before I confirm, can you send the location, expected hours, scope, kit or prep needs, rate, expense arrangements, and invoice contact? Then I can give you a clear answer.'],
   ['SCOPE CHANGE','That adds [work/time/cost] to what we agreed. Can we confirm the revised scope and pay with [approval contact] before I proceed?'],
   ['PAYMENT CHECK-IN','Hi [name], checking on invoice [number] for [job/date], sent on [date]. Could you confirm it was received and the expected payment date? Happy to resend anything you need.']
  ]},
  bridal:{stop:'STOP LETTING “JUST ONE MORE PERSON” REWRITE THE MORNING.',instead:'Confirm services, people, locations, finish time, and the cost of changes.',checklist:['Date, locations, and ready-by time','People and services confirmed','Trial or preview plan where applicable','Travel, setup, supplies, and team costs','Who approves changes','Final schedule and contact for the day'],scripts:[
   ['INQUIRY REPLY','Congratulations, [name]. To check the right setup, send your date, location, ready-by time, number of people, and the services you need. I’ll come back with availability and a clear quote.'],
   ['FINAL RECAP','Here’s the agreed plan: [people/services], at [location], starting [time], finished by [time]. The total is [price], including [items]. Please flag any changes by [agreed date] so I can check timing and staffing.'],
   ['VENDOR INTRODUCTION','Hi [name], I’m [name], a bridal stylist working in [area]. I loved [specific relevant work]. Here’s a small selection of my work and how I handle wedding mornings: [link]. I’d love to connect when you have a couple who fits.']
  ]},
  education:{stop:'STOP SELLING A TOPIC WHEN PEOPLE NEED A RESULT.',instead:'Say what they will be able to do, then price the whole assignment.',checklist:['Audience and starting skill level','One clear learning outcome','Format, duration, and location','Models, supplies, equipment, and travel','Preparation and approval deadlines','Included follow-up and how to ask for help'],scripts:[
   ['OFFER','This [format] is for [audience] who want to [practical outcome]. We’ll cover [focused content], and you’ll leave with [usable takeaway]. It includes [items], takes [time], and costs [price].'],
   ['BOOKING RECAP','Before we confirm, let’s agree on the audience, outcome, schedule, preparation, equipment, travel or supply costs, fee, and what follow-up is included.'],
   ['USEFUL FOLLOW-UP','Now that you’ve had a chance to try it: what did you use, what changed, and where are you still getting stuck? One real example is more useful than a polite review.']
  ]},
  owner:{stop:'STOP CONFUSING THE SALON’S SALES WITH YOUR PAY.',instead:'Keep team costs, building costs, your own service work, and your own pay visible.',checklist:['Collected income for the same period','Payroll or team payments','Rent, supplies, fees, and other salon costs','Your own service pay kept separate','One team or booking number to watch','Who owns each agreed action'],scripts:[
   ['TEAM FOCUS','For the next 30 days, we’re working on [one priority]. The move is [action]. We’ll watch [number], and check it on [date]. Tell me what would make this easier to do properly.'],
   ['DELEGATION','I’d like you to own [task]. You can decide [limits]. Come to me for [exceptions]. Let’s check in on [date] and adjust what is not working.'],
   ['REBOOKING HANDOFF','Before checkout, the stylist recommends [service/timing]. The desk offers the appointment and notes the outcome. [Person] handles any agreed follow-up.']
  ]},
  manager:{stop:'STOP OWNING RESULTS YOU CANNOT SEE OR INFLUENCE.',instead:'Get clear responsibility, the right information, and an agreed decision-maker.',checklist:['Your responsibilities','Decisions you can make','Decisions needing the owner','Reports you can access','Agreed pay and any bonus criteria','Off-duty handoff'],scripts:[
   ['OWNER CHECK-IN','I’m seeing [specific issue] in [report or example]. I recommend [one change]. I need your decision on [point]. Can we agree who handles it and check the result on [date]?'],
   ['PAY CONVERSATION','My role currently includes [responsibilities] and takes about [hours]. I’d like to discuss how the pay reflects that, and what specific results or responsibilities would support a review.'],
   ['BOUNDARY HANDOFF','After [time], [person/process] handles [issues]. I’ll pick up non-urgent messages at [time]. Let’s agree what genuinely needs an urgent escalation.']
  ]},
  restart:{stop:'STOP TRYING TO REBUILD AN ENTIRE CAREER BEFORE BOOKING ONE GOOD APPOINTMENT.',instead:'Get one service, one recent example, and one booking path working.',checklist:['One service you can deliver well','A suitable work setup','Current requirements for the work checked','One recent example','Price and time clearly explained','A realistic first booking goal'],scripts:[
   ['RETURNING UPDATE','Hi [name], I’m taking [service] appointments again in [location] on [days]. Here’s what I’m working on now: [link]. If that sounds like you or someone you know, [booking step].'],
   ['SALON CONVERSATION','I’m looking for a role where I can build [type of work]. Can we talk about training, schedule, pay setup, and how new stylists get support finding clients?'],
   ['MODEL INVITATION','I’m looking for [specific model/service] on [date]. The plan is [work], the time is [time], and the cost is [price]. Any photos and how they may be used will be agreed first.']
  ]},
  other:{stop:'STOP LETTING A FUZZY OFFER CREATE A FUZZY PAYCHECK.',instead:'Choose one kind of paid work and make the scope, pay, and next step clear.',checklist:['What the buyer needs','What you will deliver','Time and responsibilities','Agreed pay','Costs you actually pay','How the work is accepted and paid'],scripts:[
   ['CLEAR OFFER','I help [buyer] with [specific work/result]. Here’s an example: [link]. The next step is [simple booking or inquiry step].'],
   ['SCOPE RECAP','We agreed on [work], by [date], for [pay]. It includes [items]. If the work changes, we’ll confirm the time and price before adding it.'],
   ['FOLLOW-UP','Thanks for working with me on [job]. Was there anything that could have worked better? If you need [relevant future work], here’s the easiest way to reach me: [contact].']
  ]}
 };
 const goalNames={clients:'More of the right work',money:'Better pay for the work',return:'Repeat business and referrals',keep:'More money kept',time:'More time back',stable:'A steadier business'};
 function metricsFor(role,goal,a){
  const salon=['owner','manager'].includes(role);
  const employee=role==='manager'||a[role+'_pay']==='hourly'||a.other_format==='employment';
  if(goal==='clients')return [{id:'inquiries',label:salon?'Suitable salon inquiries':'Suitable inquiries',unit:'count',better:'up'},{id:'bookings',label:salon?'New salon bookings':'New paid bookings',unit:'count',better:'up'},{id:'completed',label:salon?'New clients who attended':'Paid bookings completed',unit:'count',better:'up'}];
  if(goal==='return')return [{id:'eligible',label:['bridal','education'].includes(role)?'Past buyers you could reasonably follow up with':'Clients or buyers due for a return',unit:'count',better:'context'},{id:'followups',label:'Relevant follow-ups completed',unit:'count',better:'context'},{id:'returns',label:role==='bridal'?'New bookings from referrals':'Repeat bookings or referred paid work',unit:'count',better:'up'}];
  if(goal==='time')return [{id:'hours',label:'Total work hours in the same length of time',unit:'hours',better:'down'},{id:'pay',label:employee?'Your pay for that time':'Money left after entered work costs',unit:'money',better:'up'},{id:'off',label:'Protected off-duty blocks kept',unit:'count',better:'up'}];
  if(goal==='stable')return [{id:'review',label:'Payday or bill check-ins completed',unit:'count',better:'up'},{id:'overdue',label:'Overdue payments you are waiting for',unit:'money',better:'down'},{id:'saved',label:'Money actually set aside after bills',unit:'money',better:'up'}];
  return [{id:'pay',label:employee?'Your actual pay':role==='owner'?'Salon money left after entered costs':'Earned pay left after entered work costs',unit:'money',better:'up'},{id:'hours',label:'Total required work hours',unit:'hours',better:'down'},{id:'costs',label:employee?'Work costs you personally pay':'Work costs paid for the same period',unit:'money',better:'context'}];
 }
 function build(input){
  const a=cleanAnswers(input);
  if(!complete(a))throw new Error('Finish the questions before building the plan.');
  const role=primary(a),profile=roles[role],goal=goalFor(a),book=playbooks[role];
  const signals=roleQuestions[role].map((q,i)=>{
   const value=a[role+'_'+q.id],values=Array.isArray(value)?value:[value];
   const labels=values.map(v=>q.choices.find(c=>c[0]===v)?.[1]).filter(Boolean);
   return {id:role+'_'+q.id,title:q.title,answer:labels.join(' / '),action:values.map(v=>q.actions[v]).filter(Boolean).join(' '),relevant:q.tags.includes(goal),order:i};
  });
  // Put an unresolved issue ahead of a routine maintenance answer within the chosen goal.
  const needsAttention=new Set(['unknown','no','rough','often','absorb','late','day','services','bundled','informal','nothing','unclear','slow','varies','lots','none']);
  const urgency=s=>{const v=a[s.id];return (Array.isArray(v)?v:[v]).some(x=>needsAttention.has(x))?1:0};
  const sorted=[...signals].sort((x,y)=>Number(y.relevant)-Number(x.relevant)||urgency(y)-urgency(x)||x.order-y.order);
  const first=sorted[0],second=sorted[1];
  const metrics=metricsFor(role,goal,a);
  const qty=a.available==='tiny'?1:a.available==='hour'?3:a.available==='two'?5:7;
  const count=a.available==='tiny'?'one':String(qty);
  const employee=role==='manager'||a[role+'_pay']==='hourly'||a.other_format==='employment';
  const labels={clients:a.load==='full'?'BETTER-FIT WORK. NOT A BIGGER PILE OF IT.':'MAKE THE NEXT BOOKING EASIER TO SAY YES TO.',money:employee?'MAKE THE WORK AND THE PAY MATCH.':'MAKE THE WORK PAY FOR THE TIME IT TAKES.',return:role==='bridal'?'LET A GOOD EVENT LEAD TO THE NEXT ONE.':'GIVE GOOD WORK A NEXT APPOINTMENT.',keep:'FIND WHAT THE BIG NUMBER IS HIDING.',time:'YOUR CALENDAR DOES NOT GET CUSTODY OF YOUR LIFE.',stable:'BUILD A BUSINESS THAT CAN HANDLE A WEIRD WEEK.'};
  let baseline=goal==='clients'?'For '+count+' recent inquiries, note where they came from and whether they became paid work.':goal==='return'?'Choose '+count+' past clients or buyers who could reasonably return or refer someone. Note what actually happened.':goal==='time'?'Record one normal workday, including prep, travel, messages, and cleanup. Keep the pay for that same day beside it.':goal==='stable'?'Check the bills due before your next payment and the money actually available. Keep money owed to you separate.':employee?'Use one actual pay period. Record the pay, all required hours, and work costs you personally paid.':'Use one normal '+profile.unit+'. Record earned pay, the costs you paid, and all the time the work took.';
  if(role==='owner'&&(goal==='money'||goal==='keep'))baseline='Use one normal salon day or month. Keep collected income, payroll, rent, products, fees, and what you paid yourself separate.';
  let firstAction=first.action;
  if(goal==='stable')firstAction=a.savings==='unknown'?'Find the savings you could actually use and the bills it needs to cover. Unknown is a starting point, not a personality flaw.':a.savinghabit==='bills'?'Start with upcoming bills and one way to improve income or work costs. Do not promise a savings transfer the current money cannot support.':a.savings==='solid'?'Check what the cushion is for and keep it separate from money for planned spending.':'At the next payment, cover upcoming bills first. If money is available, choose a manageable amount to set aside.';
  const scripts=book.scripts.map(x=>[...x]);
  if(employee&&role!=='manager')scripts[2]=['PAY CONVERSATION','My work currently includes [responsibilities] and takes [required hours]. Can we review how my pay is calculated, what supports a pay review, and when we can revisit it? Here is one example of my contribution: [example].'];
  const returnScript={color:1,cut:1,extensions:1,session:0,bridal:2,education:2,owner:2,manager:0,restart:0,other:2};
  const script=employee&&goal==='money'?scripts[role==='manager'?1:2]:goal==='clients'?scripts[0]:goal==='return'?scripts[returnScript[role]]:scripts[1];
  const practice=goal==='stable'?'At the next payday or bill check-in, repeat the check with the money actually available. Record what you could set aside after bills, even if it was $0.':goal==='keep'?'Recheck one comparable '+profile.unit+' after your first change. Include the same costs. Record whether more money stayed with you.':'Use “'+script[0]+'” below in '+count+' real situation'+(qty===1?'':'s')+'. Replace the brackets with what is true for you.'+(employee&&goal==='money'?' Agree on the review process and the next decision. A raise is a conversation, not a forecast.':'');
  const missions=[
   {week:1,title:'GET ONE HONEST BASELINE.',tasks:[baseline,'Write down the starting value for “'+metrics[0].label+'” in the scorecard. If you do not know it yet, leave it blank and collect it before comparing.'],watch:metrics[0].label},
   {week:2,title:'TRY THE FIRST CHANGE.',tasks:[firstAction,goal==='clients'&&a.budget==='0'?'Use existing contacts, relevant referrals, and the work you already have. No paid ads, new software, or rebrand required.':second.action],watch:metrics[0].label+' and '+metrics[1].label},
   {week:3,title:'REPEAT IT. KEEP THE RECEIPTS.',tasks:[practice,'Write down what happened. A reply, booking, completed job, payment, or hour saved counts. A vague feeling does not.'],watch:metrics[metrics.length-1].label},
   {week:4,title:'KEEP THE WINNER. FIX THE REST.',tasks:['Compare the same length of time before and after the change using the scorecard below.','If the change helped, repeat it. If it did not, change one thing and run a smaller test. Use the “If it gets stuck” section to choose the next move.'],watch:'What changed in the work, money, or time you actually recorded.'}
  ];
  if(a.available==='tiny')for(const week of missions)week.tasks=week.tasks.slice(0,1);
  const control=a[role+'_control'];
  const constraints=[];
  if(control==='salon'||control==='together'||role==='manager')constraints.push('Changes to pricing, pay, or team rules need the right person’s agreement. The plan uses proposals where you do not control the decision.');
  if(a.available==='tiny')constraints.push('This is the small version: one focused task each week. Do it during work where practical. Add depth only when you have room.');
  if(a.load==='starting'||a.load==='open')constraints.push('There is room for more paid work. A fuller book has to be earned; this plan does not assume demand supports a price increase.');
  if(a.load==='full')constraints.push('You said the work is already full or close to it. Better money or better-fit work matters more than squeezing in another day.');
  if(goal==='clients'&&a.budget&&a.budget!=='0')constraints.push('A marketing budget is a limit, not an instruction to spend it. Start small and track completed paid work before spending more.');
  return {version:VERSION,role,roleLabel:profile.label,goal,goalLabel:goalNames[goal],headline:labels[goal],intro:'Your '+profile.label.toLowerCase()+' plan starts with '+goalNames[goal].toLowerCase()+'. One priority. Four weeks. Useful work.',
   doNow:firstAction,stop:book.stop,instead:book.instead,watch:metrics[0].label,metrics,missions,
   evidence:sorted.slice(0,3),supporting:signals,checklist:book.checklist,scripts,constraints,
   secondary:(a.careers||[]).filter(x=>x!==role).map(x=>({role:x,label:roles[x].label,first:playbooks[x].instead})),
   rescue:[{title:'NOBODY BOOKED.',body:'Check the offer, the person it reached, and whether booking was clear. Start with one relevant conversation before changing every price or buying more ads.'},{title:'THE MONEY DID NOT IMPROVE.',body:'Compare the same kind of work with the same costs included. Separate money earned from reimbursements and money still unpaid. Change one cost, scope, or pay conversation at a time.'},{title:'THE PLAN DID NOT FIT YOUR WEEK.',body:'Keep one task and make it smaller. One recorded appointment or one useful conversation is enough to start.'},{title:'YOU NEED SOMEONE ELSE TO SAY YES.',body:'Bring one clear example, one proposed change, and the decision you need. Agree on who owns the next step and when to revisit it.'}],
   tool:{title:profile.tool,earnedLabel:employee?'Actual pay for the period you are checking':role==='owner'?'Collected salon income for the day or period':'Earned service or job fee, excluding reimbursements',costLabel:employee?'Work costs you personally paid':role==='extensions'?'Hair, supplies, and other costs you paid':role==='bridal'?'Team pay, travel, supplies, and other costs you paid':role==='owner'?'Payroll, rent allocated to this period, supplies, fees, and other costs':'Costs you paid and will not be reimbursed for',hoursLabel:'All required work hours for that same work or period',share:!employee&&['color','cut','extensions','restart','other'].includes(role),warning:employee?'This compares your entered pay and costs with required time. It does not infer a raise or replace your pay records.':role==='owner'?'This is an operating remainder from the costs entered, not automatically the owner’s take-home pay. Unentered costs and taxes are excluded.':'This is the amount left after the pay split and costs entered, before personal taxes and any omitted business bills.'},
   answers:questions(a).map(q=>({id:q.id,title:q.title,answer:(Array.isArray(a[q.id])?a[q.id]:[a[q.id]]).map(v=>q.choices.find(x=>x[0]===v)?.[1]).filter(Boolean).join(' / ')}))
  };
 }
 function workMath({earned,costs,hours,share=100}){
  if(![earned,costs,hours,share].every(Number.isFinite)||earned<0||costs<0||hours<=0||share<0||share>100)return null;
  const left=earned*share/100-costs;
  return {left,perHour:left/hours,earned,costs,hours,share};
 }
 function valueMath({additionalKept,extraCosts=0,price=PRICE}){
  if(![additionalKept,extraCosts,price].every(Number.isFinite)||extraCosts<0||price<0)return null;
  const benefit=additionalKept-extraCosts;
  return {benefit,afterPurchase:benefit-price,returnPercent:price===0?null:(benefit-price)/price*100,breakEven:benefit>=price};
 }
 function breakEven(amount,price=PRICE){return Number.isFinite(amount)&&amount>0&&Number.isFinite(price)&&price>=0?Math.ceil(price/amount):null}
 return {VERSION,PRICE,roles,examples,goals,questions,choices,primary,goalFor,cleanAnswers,complete,seed,build,workMath,valueMath,breakEven};
})();
