const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {JSDOM}=require('jsdom'),P=require('../next30-rebooking.js');
const row=(extra={})=>({id:'a',client:'client-a',guest:'new',service:'Color',source:'Referral',visit:'2026-01-01',minWeeks:'4',maxWeeks:'8',recommended:'yes',eligible:'yes',rebooked:'yes',nextDate:'2026-02-05',cancelled:'no',returned:'yes',returnDate:'2026-02-05',reason:'',...extra});
const asOf='2026-04-01';
let s=P.stats([row(),row({id:'b',client:'client-b',returned:'no',returnDate:'',rebooked:'no',nextDate:'',cancelled:'unknown'}),row({id:'c',client:'client-c',visit:'2026-03-01',nextDate:'2026-04-10',returned:'no',returnDate:''}),row({id:'d',client:'client-d',returned:'unknown',returnDate:''})],asOf);
assert.equal(s.overall.rebooking.pct,75);assert.equal(s.overall.retention.d,2);assert.equal(s.overall.retention.pct,50);assert.equal(s.overall.pending,1);assert.equal(s.overall.unknownReturns,1);
assert.equal(s.overall.cancellations.d,2,'A future prebook must not enter the cancellation denominator');
assert.equal(P.stats([],asOf).overall.retention.pct,null,'No evidence must not display 0%');
assert.equal(P.stats([row()], '2026-02-26').overall.pending,1,'The last day of the service window is still pending');
assert.equal(P.stats([row()], '2026-02-27').overall.retention.pct,100);
assert.equal(P.stats([row(),row({id:'b'})],asOf).overall.retention.d,1,'Repeated client IDs must not inflate retained-client counts');
assert.equal(P.stats([row(),row({id:'later',visit:'2026-03-01',nextDate:'2026-04-10',returned:'unknown',returnDate:''})],asOf).overall.retention.d,1,'A new pending visit must not erase an older matured cohort');
assert.equal(P.stats([row({maxWeeks:'16',returned:'no',returnDate:''})],asOf).overall.retention.d,0,'Use this service window, not a universal benchmark');
assert.equal(P.stats([row({rebooked:'no',nextDate:''})],asOf).overall.retention.pct,100,'Actual return does not require prebooking');
assert.equal(P.stats([row({rebooked:'unknown'})],asOf).overall.rebooking.pct,null);
assert.equal(P.stats([row({cancelled:'unknown'})],asOf).overall.cancellations.pct,null);
assert.equal(P.stats([row({eligible:'no'})],asOf).overall.rebooking.d,0);
assert.equal(P.stats([row({returnDate:'2026-01-05'})],asOf).overall.retention.n,0,'An early unrelated visit does not prove return inside the service window');
assert.equal(P.stats([row({returnDate:'2026-05-05'})],asOf).overall.invalid,1);
assert(P.validate(row({maxWeeks:'2'}),asOf));assert(P.validate(row({visit:'2026-02-30'}),asOf));
let c=P.coverage({total:'100',blocked:'20',returning:'40',newClients:'10'});assert.equal(c.available,80);assert.equal(c.returning,50);assert.equal(c.total,62.5);assert.equal(c.remaining,30);
assert(P.coverage({total:'100',blocked:'',returning:'0',newClients:'0'}).error,'Unknown blocked capacity must not become zero');
assert(P.coverage({total:'20',blocked:'20',returning:'0',newClients:'0'}).error);assert(P.coverage({total:'20',blocked:'5',returning:'16',newClients:'0'}).error);
assert.match(P.csv([row({client:'=HYPERLINK("bad")'})]),/"'=HYPERLINK/);
async function boot(paid=true,saved=null,url=null){
 const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:url||'https://preview.example.test/?next30=paid&session_id=cs_test_Example123',runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window,ctx=dom.getInternalVMContext(),errors=[];w.scrollTo=()=>{};w.AbortSignal=AbortSignal;w.addEventListener('error',e=>errors.push(e.error));
 w.fetch=async url=>({ok:true,json:async()=>String(url).includes('verify-checkout')?{paid}:{ready:true,schemas:['short-v5']}});
 if(saved)w.localStorage.setItem('booked-af-career-next30-v2',saved);
 for(const f of ['day-math.js','breakdown-core.js','site-content.js','next30-core.js','next30-ui.js','next30-rebooking.js','next30-shell.js','app.js','lifecycle-ui.js','site-ui.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
 await new Promise(r=>setTimeout(r,25));
 const run=c=>vm.runInContext(c,ctx),$=s=>w.document.querySelector(s),input=(id,v)=>{const x=$('#'+id);assert(x,id);x.value=String(v);x.dispatchEvent(new w.Event('input',{bubbles:true}))};
 return {dom,w,run,$,input,errors};
}
(async()=>{
 let b=await boot(true,null,'https://bookedandfabulous.com/#my-plans');assert(b.$('#resume-paid').hidden,'Production does not grant preview access');b.dom.window.close();
 b=await boot(true,null,'https://branch-booked-af-email.example.workers.dev/#my-plans');assert(!b.$('#resume-paid').hidden);b.$('#resume-paid').click();assert.equal(b.run('state.deepPreview'),true);assert.equal(b.run('state.view'),'deepintake');b.dom.window.close();
 b=await boot(false);assert(!b.$('#rebooking-tracker'),'Unverified checkout must not expose the paid tracker');b.dom.window.close();
 b=await boot();let {w,run,$,input}=b;
 run(`let a={careers:['color'],goal:'return',color_pay:'commission'};for(let pass=0;pass<8;pass++){for(const q of BookedNext30.questions(a))if(a[q.id]===undefined)a[q.id]=q.multi?[q.choices[0][0]]:q.choices[0][0];a=BookedNext30.cleanAnswers(a)}state.careerData={version:BookedNext30.VERSION,answers:a,carried:{},checks:{},metrics:{},tools:{},savedPlans:[],shell:{}};state.view='deepresult';render()`);
 assert($('#rebooking-tracker'),'Return goal opens P02 directly');
 input('p02-asof',asOf);$('#p02-asof').dispatchEvent(new w.Event('change'));
 for(const [k,v] of Object.entries(row()))if(k!=='id')input('p02-'+k,v);
 $('#p02-form').dispatchEvent(new w.Event('submit',{cancelable:true}));
 assert.equal(run('state.careerData.shell.rebooking.rows.length'),1);assert.match($('#p02-summary').textContent,/100.0%/);
 $('[data-p02-edit]').click();input('p02-client','<script>alert(1)</script>');$('#p02-form').dispatchEvent(new w.Event('submit',{cancelable:true}));
 assert.equal(run('state.careerData.shell.rebooking.rows.length'),1);assert(!$('#p02-rows script'),'Client text is escaped');
 for(const [k,v] of Object.entries({total:100,blocked:20,returning:40,newClients:10}))input('p02-cov-4-'+k,v);
 $('#p02-cov-calc').click();assert.match($('#p02-cov-result-4').textContent,/50.0%/);
 $('[data-p02-week]').checked=true;$('[data-p02-week]').dispatchEvent(new w.Event('change'));
 input('p02-client','draft-client');
 const saved=w.localStorage.getItem('booked-af-career-next30-v2');assert.equal(b.errors.length,0);b.dom.window.close();
 b=await boot(true,saved);({w,run,$,input}=b);run(`state.view='deepresult';render()`);
 assert.equal($('#p02-client').value,'draft-client');assert($('[data-p02-week]').checked);assert.equal($('#p02-cov-4-total').value,'100');assert.equal(run('state.careerData.shell.rebooking.rows.length'),1);
 // Select P02 from the money-path result, rather than only entering directly.
 run(`state.careerData.answers.goal='money';state.careerData.shell.nextPath='p02';render()`);assert($('#rebooking-tracker'));
 $('[data-p02-delete]').click();assert.equal(run('state.careerData.shell.rebooking.rows.length'),0);
 run("state.view='privacy';render()");$('[data-clear-progress]').click();assert.equal(w.localStorage.getItem('booked-af-career-next30-v2'),null);assert.equal(run('state.careerData'),null);
 assert.equal(b.errors.length,0);b.dom.window.close();
 console.log('PASS: P02 service windows, honest denominators, unique clients, capacity math, protected entry, direct and money routes, edit/delete, reload, draft save, escaping and clear progress.');
})().catch(e=>{console.error(e);process.exitCode=1});
